[package]
name = "axum-serve"
version = "0.1.0"
edition = "2021"

[features]
default = [ "threads", "log-spans" ]
threads = [ "tokio/rt-multi-thread" ]
log = []
log-headers = ["log"]
log-spans = ["log"]

[dependencies]
# Server
axum = "0.5.17"
tower-http = { version = "0.3.4", features = ["trace", "catch-panic"] }
hyper = { version = "0.14.20", default-features = false }

# Runtime
tokio = { version = "1.21.2", features = ["signal"] }

# Error
thiserror = "1.0.37"

# Trace
tracing = "0.1.37"
tracing-subscriber =  "0.3.16"
chrono = "0.4.22"
rand = "0.8.5"
